# Example from here 
https://github.com/bayespy/bayespy/issues/23

In [1]:
import numpy as np

from bayespy.nodes import Categorical, Mixture
from bayespy.inference import VB



In [42]:
# NOTE: Python's built-in booleans don't work nicely for indexing, thus define
# own variables:
FALSE = 0
TRUE = 1

object_presence = Categorical([0.8, 0.2])
detection_probability = Mixture(object_presence, Categorical, [[0.81, 0.19], [0.8, 0.2]])

detection_probability.observe(FALSE)
Q = VB( detection_probability, object_presence)
Q.update(repeat=100)

detection_probability = Mixture(object_presence, Categorical, [[0.81, 0.19], [0.8, 0.2]])
detection_probability.observe(FALSE)
Q = VB( detection_probability, object_presence)
Q.update(repeat=100)
detection_probability = Mixture(object_presence, Categorical, [[0.81, 0.19], [0.8, 0.2]])
detection_probability.observe(FALSE)
Q = VB( detection_probability, object_presence)
Q.update(repeat=100)
# Show results
print("P(object_presence):", object_presence.get_moments()[0][TRUE])
print("P(detection_probability):", detection_probability.get_moments()[0][TRUE])

Iteration 1: loglike=-2.131932e-01 (0.001 seconds)
Iteration 2: loglike=-2.131932e-01 (0.001 seconds)
Converged at iteration 2.
Iteration 1: loglike=-2.132054e-01 (0.002 seconds)
Iteration 2: loglike=-2.132054e-01 (0.002 seconds)
Converged at iteration 2.
Iteration 1: loglike=-2.132417e-01 (0.002 seconds)
Iteration 2: loglike=-2.132417e-01 (0.001 seconds)
Converged at iteration 2.
P(object_presence): 0.194103793971
P(detection_probability): 0.0


In [21]:
asia = Categorical([0.5, 0.5])

tuberculosis = Mixture(asia, Categorical, [[0.99, 0.01], [0.8, 0.2]])

# Mark observations
tuberculosis.observe(FALSE)

# Run inference
Q = VB(tuberculosis, asia)
Q.update(repeat=100)

# Show results
print("P(asia):", asia.get_moments()[0][TRUE])
print("P(tuberculosis):", tuberculosis.get_moments()[0][TRUE])

Iteration 1: loglike=-1.109316e-01 (0.002 seconds)
Iteration 2: loglike=-1.109316e-01 (0.001 seconds)
Converged at iteration 2.
P(asia): 0.446927374302
P(tuberculosis): 0.0


# pymc bayesian model

https://healthyalgorithms.com/2011/11/23/causal-modeling-in-python-bayesian-networks-in-pymc/


Didnt understand anyhting . Dont know what lambda is 

In [44]:
import pylab as pl
import pymc as mc
 
G_obs = [1.]
N = len(G_obs)
 
R = mc.Bernoulli('R', .2, value=pl.ones(N))
 
p_S = mc.Lambda('p_S', lambda R=R: pl.where(R, .01, .4),
                doc='Pr[S|R]')
S = mc.Bernoulli('S', p_S, value=pl.ones(N))
 
p_G = mc.Lambda('p_G', lambda S=S, R=R:
                pl.where(S, pl.where(R, .99, .9), pl.where(R, .8, 0.)),
                doc='Pr[G|S,R]')
G = mc.Bernoulli('G', p_G, value=G_obs, observed=True)

# again Bayespy

Using the example from the Dirichlet-Categorical-Bernouli example 

In [56]:
import bayespy as bp


# Concentration parameter
# adding parameter to share information between the different timezones
p = bp.nodes.Dirichlet([0.6,0.2,0.2]) # wito
locations = bp.nodes.Categorical(p, plates=(1,))
observations = bp.nodes.Mixture(
    locations,
    bp.nodes.Bernoulli,
    [
        [0.2, 0.8, 0.8],
    ]
)
observations.observe([True])
Q = bp.inference.VB(observations, locations, p)
Q.update(repeat=10)
print(locations)

observations = bp.nodes.Mixture(
    locations,
    bp.nodes.Bernoulli,
    [
        [0.2, 0.8, 0.8],
    ]
)
observations.observe([True])
Q = bp.inference.VB(observations, locations, p)
Q.update(repeat=10)
print(locations)

observations = bp.nodes.Mixture(
    locations,
    bp.nodes.Bernoulli,
    [
        [0.2, 0.8, 0.8],
    ]
)
observations.observe([True])
Q = bp.inference.VB(observations, locations, p)
Q.update(repeat=10)
print(locations)

observations = bp.nodes.Mixture(
    locations,
    bp.nodes.Bernoulli,
    [
        [0.2, 0.8, 0.8],
    ]
)
observations.observe([True])
Q = bp.inference.VB(observations, locations, p)
Q.update(repeat=10)
print(locations)

Iteration 1: loglike=-2.067864e+00 (0.002 seconds)
Iteration 2: loglike=-2.067860e+00 (0.002 seconds)
Converged at iteration 2.
 ~ Categorical(p)
  p = 
[[ 0.84216465  0.07891767  0.07891767]]

Iteration 1: loglike=-2.037021e+00 (0.002 seconds)
Iteration 2: loglike=-1.944622e+00 (0.002 seconds)
Iteration 3: loglike=-1.968142e+00 (0.002 seconds)
Converged at iteration 3.
 ~ Categorical(p)
  p = 
[[ 0.05477229  0.47261385  0.47261385]]

Iteration 1: loglike=-2.030486e+00 (0.002 seconds)
Iteration 2: loglike=-2.034439e+00 (0.003 seconds)
Converged at iteration 2.
 ~ Categorical(p)
  p = 
[[ 0.00584818  0.49707591  0.49707591]]

Iteration 1: loglike=-2.048906e+00 (0.003 seconds)
Iteration 2: loglike=-2.049038e+00 (0.002 seconds)
Converged at iteration 2.
 ~ Categorical(p)
  p = 
[[ 0.00142585  0.49928708  0.49928708]]



/home/deebuls/anaconda3/lib/python3.5/site-packages/bayespy/inference/vmp/vmp.py:734: UserWarning: Lower bound decreased 2.352017e-02! Bug somewhere or numerical inaccuracy?
  "numerical inaccuracy?" % L_diff)
/home/deebuls/anaconda3/lib/python3.5/site-packages/bayespy/inference/vmp/vmp.py:734: UserWarning: Lower bound decreased 3.952753e-03! Bug somewhere or numerical inaccuracy?
  "numerical inaccuracy?" % L_diff)
/home/deebuls/anaconda3/lib/python3.5/site-packages/bayespy/inference/vmp/vmp.py:734: UserWarning: Lower bound decreased 1.316867e-04! Bug somewhere or numerical inaccuracy?
  "numerical inaccuracy?" % L_diff)


# Code 

Modelling from the statistics for spatio temporal data -> page 25


In [103]:
class fault_tolerant_probabilistic_search:
    
    def __init__(self, occurrence_probability, detection_probability):
        
        assert (0.0 <= detection_probability <= 1.0) , \
            "Detection probability is not in range [0.0 - 1.0]"
        assert (0.99 <= sum(occurrence_probability) <= 1.01 ), \
            "Probabilities dont add up to 1"
            
        self.occurrence_probability = occurrence_probability
        self.detection_probability = detection_probability
        
        self.first = True
        
    def show(self):
        
        print ("Probabilities : ", self.occurrence_probability)
        
    def next_location_to_search(self):
        if self.first:
            #do nothing in first
            self.first = False
        else :
            # Previous location search failed
            # updating probabilities
            max_value = max(self.occurrence_probability)
            max_index = self.occurrence_probability.index(max_value)
            for index, value in enumerate(self.occurrence_probability):
                if max_index == index:
                    new_prob = ((1 - self.detection_probability) * max_value) / \
                                    (1 - max_value*self.detection_probability)
                else:
                    #TODO : is it max_value(i.e. old max prob ) or new prob
                    new_prob = value / (1 - self.detection_probability*max_value)
                    
                self.occurrence_probability[index] = new_prob
                    
            
        max_value = max(self.occurrence_probability)
        max_index = self.occurrence_probability.index(max_value)
        self.show()
        return (max_index)


In [105]:
a = fault_tolerant_probabilistic_search([0.33, 0.33, 0.33], 0.8)
#a = fault_tolerant_probabilistic_search([1, 2, 2], 0.5)
#a = fault_tolerant_probabilistic_search([0.33, 0.33, 0.33], 1.5)
print (a.next_location_to_search())
print (a.next_location_to_search())
print (a.next_location_to_search())
print (a.next_location_to_search())
print (a.next_location_to_search())
print (a.next_location_to_search())
print (a.next_location_to_search())

Probabilities :  [0.33, 0.33, 0.33]
0
Probabilities :  [0.08967391304347824, 0.44836956521739135, 0.44836956521739135]
1
Probabilities :  [0.13983050847457626, 0.13983050847457626, 0.6991525423728815]
2
Probabilities :  [0.3173076923076924, 0.3173076923076924, 0.3173076923076924]
0
Probabilities :  [0.08505154639175261, 0.42525773195876304, 0.42525773195876304]
1
Probabilities :  [0.12890625000000008, 0.12890625000000006, 0.6445312500000003]
2
Probabilities :  [0.2661290322580649, 0.26612903225806483, 0.2661290322580648]
0


In [106]:

a = fault_tolerant_probabilistic_search([0.8, 0.1, 0.1], 0.8)
a = fault_tolerant_probabilistic_search([0.33, 0.33, 0.33], 0.8)
#a = fault_tolerant_probabilistic_search([1, 2, 2], 0.5)
#a = fault_tolerant_probabilistic_search([0.33, 0.33, 0.33], 1.5)
print (a.next_location_to_search())
print (a.next_location_to_search())
print (a.next_location_to_search())
print (a.next_location_to_search())
print (a.next_location_to_search())
print (a.next_location_to_search())
print (a.next_location_to_search())
#a = fault_tolerant_probabilistic_search([1, 2, 2], 0.5)
#a = fault_tolerant_probabilistic_search([0.33, 0.33, 0.33], 1.5)
print (a.next_location_to_search())
print (a.next_location_to_search())
print (a.next_location_to_search())
print (a.next_location_to_search())
print (a.next_location_to_search())
print (a.next_location_to_search())
print (a.next_location_to_search())

Probabilities :  [0.8, 0.1, 0.1]
0
Probabilities :  [0.44444444444444453, 0.2777777777777779, 0.2777777777777779]
0
Probabilities :  [0.13793103448275865, 0.43103448275862094, 0.43103448275862094]
1
Probabilities :  [0.2105263157894738, 0.13157894736842116, 0.6578947368421059]
2
Probabilities :  [0.4444444444444452, 0.2777777777777783, 0.2777777777777783]
0
Probabilities :  [0.13793103448275895, 0.4310344827586219, 0.4310344827586219]
1
Probabilities :  [0.21052631578947448, 0.13157894736842157, 0.657894736842108]
2
